openapi: 3.0.0

info:
  title: JOBS-API

  contact: {}

  version: "1.0"

servers:
  - url: https://mo-jobs-api-v1.herokuapp.com/api/v1

    variables: {}

paths:
  /auth/register:
    post:
      tags:
        - Auth

      summary: Register

      operationId: Register

      parameters: []

      requestBody:
        description: ""

        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"

            example:
              username: momo2020

              email: momo2@gmail.com

              password: "123123"

        required: true

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      servers:
        - url: https://mo-jobs-api-v1.herokuapp.com/api/v1

          variables: {}

  /auth/login:
    post:
      tags:
        - Auth

      summary: Login

      operationId: Login

      parameters: []

      requestBody:
        description: ""

        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"

            example:
              email: momo@gmail.com

              password: secret123

        required: true

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      servers:
        - url: https://mo-jobs-api-v1.herokuapp.com/api/v1

          variables: {}

  /auth/updateUser:
    patch:
      tags:
        - Auth

      summary: updateUser

      operationId: updateUser

      parameters: []

      requestBody:
        description: ""

        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserRequest"

            example:
              username: momo2020

              email: momo@gmail.com

              location: my location

        required: true

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security:
        - bearer: []

      servers:
        - url: https://mo-jobs-api-v1.herokuapp.com/api/v1

          variables: {}

  /jobs:
    get:
      tags:
        - Jobs

      summary: Get All jobs

      operationId: GetAlljobs

      parameters: []

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security:
        - bearer: []

      servers:
        - url: https://mo-jobs-api-v1.herokuapp.com/api/v1

          variables: {}

    post:
      tags:
        - Jobs

      summary: Create Job

      operationId: CreateJob

      parameters: []

      requestBody:
        description: ""

        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateJobRequest"

            example:
              company: The tech

              position: intern

        required: true

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security:
        - bearer: []

      servers:
        - url: https://mo-jobs-api-v1.herokuapp.com/api/v1

          variables: {}

  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: the job id
    get:
      tags:
        - Jobs

      summary: Get Single Job

      operationId: GetSingleJob

      parameters: []

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security:
        - bearer: []

      servers:
        - url: https://mo-jobs-api-v1.herokuapp.com/api/v1

          variables: {}

    patch:
      tags:
        - Jobs

      summary: Update Job

      operationId: UpdateJob

      parameters: []

      requestBody:
        description: ""

        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateJobRequest"

            example:
              company: The tech

              position: intern

        required: true

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security:
        - bearer: []

      servers:
        - url: https://mo-jobs-api-v1.herokuapp.com/api/v1

          variables: {}

    delete:
      tags:
        - Jobs

      summary: Delete Job

      operationId: DeleteJob

      parameters: []

      responses:
        "200":
          description: ""

          headers: {}

      deprecated: false

      security:
        - bearer: []

      servers:
        - url: https://mo-jobs-api-v1.herokuapp.com/api/v1

          variables: {}

components:
  schemas:
    RegisterRequest:
      title: RegisterRequest

      required:
        - username

        - email

        - password

      type: object

      properties:
        username:
          type: string

        email:
          type: string

        password:
          type: string

      example:
        username: momo2020

        email: momo2@gmail.com

        password: "123123"

    LoginRequest:
      title: LoginRequest

      required:
        - email

        - password

      type: object

      properties:
        email:
          type: string

        password:
          type: string

      example:
        email: momo@gmail.com

        password: secret123

    UpdateUserRequest:
      title: UpdateUserRequest

      required:
        - username

        - email

        - location

      type: object

      properties:
        username:
          type: string

        email:
          type: string

        location:
          type: string

      example:
        username: momo2020

        email: momo@gmail.com

        location: my location

    CreateJobRequest:
      title: CreateJobRequest

      required:
        - company

        - position

      type: object

      properties:
        company:
          type: string

        position:
          type: string

      example:
        company: The tech

        position: intern

    UpdateJobRequest:
      title: UpdateJobRequest

      required:
        - company

        - position

      type: object

      properties:
        company:
          type: string

        position:
          type: string

      example:
        company: The tech

        position: intern

    DeleteJobRequest:
      title: DeleteJobRequest

      required:
        - company

        - position

      type: object

      properties:
        company:
          type: string

        position:
          type: string

      example:
        company: The tech

        position: intern

  securitySchemes:
    bearer:
      type: http

      scheme: bearer

security: []

tags:
  - name: Auth

  - name: Jobs

